WIP: Filling in information
icu-hearts/icu-hearts.github.io pull request #5
Opened 2024-11-25 11:42 UTC by RosalynLP

Adding existing information to website 
- [ ] profiles
- [ ] footer and links
- [ ] our team
- [ ] current work
- [ ] our vision

Idea is to put in a basic small amount of info which we can build on - but remove the lorem ipsum

2024-12-02 15:05 UTC, RosalynLP commented
We still need to add the rest of the team's profiles before we can merge

2024-12-05 11:24 UTC, sjrhode requested changes
Header + footer not appearing in chrome. Errors: 
```
Access to fetch at 'icu-hearts.github.io/footer.html' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: chrome, chrome-extension, chrome-untrusted, data, http, https, isolated-app.Understand this errorAI
footer.html:1 
        
       Failed to load resource: net::ERR_FAILEDUnderstand this errorAI
index.html:161 Error loading footer: TypeError: Failed to fetch
    at index.html:156:7
```

2024-12-09 11:02 UTC, RosalynLP commented
> Header + footer not appearing in chrome. Errors:
> 
> ```
> Access to fetch at 'icu-hearts.github.io/footer.html' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: chrome, chrome-extension, chrome-untrusted, data, http, https, isolated-app.Understand this errorAI
> footer.html:1 
>         
>        Failed to load resource: net::ERR_FAILEDUnderstand this errorAI
> index.html:161 Error loading footer: TypeError: Failed to fetch
>     at index.html:156:7
> ```

I **think** this could be a problem which will disappear once deployed to GitHub pages - access to local files is being blocked by certain browsers but once this is deployed it won't be trying to access local files anymore, just the ones on GitHub. We can test and see...

2024-12-13 09:41 UTC, RosalynLP commented
@sjrhode if you're happy to merge this next week then go ahead :) 

It will let us see if the header/footer issue persists on GitHub pages

We can add other team members and collaborators in the future

2025-01-13 09:03 UTC, sjrhode approved these changes
looks good! Need to check footer when deployed

2025-01-13 09:03 UTC, merged